name: Release
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Build step
        run: |
          npm run build

      - name: Build PLUG.md
        run: |
          mv PLUG.md PLUG_SRC.md
          m4 PLUG_SRC.md > PLUG.md

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          files: |
            worker/silversearch.plug.js
            PLUG.md